name: photo_list
description: Mobile application showing list of phots from unsplash

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0
  cupertino_icons: ^1.0.4
  freezed_annotation: ^2.0.3
  retrofit: ^3.0.1+1
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  connectivity_plus: ^2.3.0
  flutter_bloc: ^8.0.1
  dartz: ^0.10.1
  dio: ^4.0.6
  json_serializable: ^6.2.0
  equatable: ^2.0.3
  get_it: ^7.2.0
  network_image_mock: ^2.1.0
  url_launcher: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  hive_generator: ^1.1.3
  retrofit_generator: ^4.0.1
  bloc_test: ^9.0.3



flutter:
  generate: true
  uses-material-design: true
  assets:
    - "assets/pixabay_logo.png"